In [ ]:
import torch

ten1 = torch.rand(10)

print(ten1)
print("hi")

In [ ]:
import torch

tensor1 = torch.rand(9); tensor1 = tensor1.view(3, 3)

padded = torch.nn.functional.pad(tensor1, (1, 1, 1, 1), mode='constant', value=0)
print(padded)



In [ ]:
class ConductiveSurface:
    def __init__(self, length: int, width: int):
        self.atoms = torch.Tensor(length, width).fill_(0)
    
    def heat_square(self, loc: tuple = (0, 0), radius: int = 2, temperature: float = 0.5) -> None:
        padded = torch.nn.functional.pad(self.atoms, (radius, radius, radius, radius), mode='constant', value=0)
        
        # change region around loc to temperature
        x = torch.arange(padded.shape[1])
        y = torch.arange(padded.shape[0])
        xx, yy = torch.meshgrid(x, y)
        dist = ((xx - loc[0]) ** 2 + (yy - loc[1]) ** 2).sqrt()
        mask = dist <= radius
        padded[mask] = temperature
        
        # unpad
        self.atoms = padded[radius:-radius, radius:-radius]
            
    def get_iterable(self) -> torch.Tensor:
        return self.atoms

surf1 = ConductiveSurface(length=10, width=10)
print(surf1.get_iterable())
surf1.heat_square((5, 5), 2, 9)

print(surf1.get_iterable())

In [ ]:
import torch

tensor1 = torch.rand(9); tensor1 = tensor1.view(3, 3)

shifted_left = torch.roll(tensor1, shifts=1)
shifted_left[:, -1] = 0

print(shifted_left)

In [ ]:
import torch

tensor1 = torch.rand(9); tensor1 = tensor1.view(3, 3)

padded = torch.nn.functional.pad(tensor1, (1, 1, 1, 1), mode='constant', value=0)
print(padded)



In [1]:
import torch

tensor1 = torch.rand(9); tensor1 = tensor1.view(3, 3)

for row in tensor1:
    print(row)

tensor([0.6198, 0.9183, 0.8398])
tensor([0.1816, 0.4457, 0.5548])
tensor([0.7890, 0.0663, 0.5451])


In [4]:
import numpy as np

testli = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]
ndarr = np.array(testli)
print(ndarr)
ndarr[0] = [(9, 10), 10, 11]
print(ndarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


ValueError: setting an array element with a sequence. The requested array would exceed the maximum number of dimension of 1.